name: Lint, Test & Deploy
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  workflows_asked:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build scripts
        run: npm run build
      - name: Message
        run: echo "Deploying project as part of workflow"